import { Track } from '@nonsololarco/types';

export const MOCK_CURRENT_USER_ID = 'mock-user-solomiia';

export const MOCK_ALL_REPERTOIRE: Track[] = [
  // --- band-1 · Quiet Yard (6 tracks, 5 ready) ---
  {
    id: 't-1',
    order: 1,
    title: 'Yard in the fog',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-1', name: 'Quiet Yard' },
    side: 'a',
    musicalKey: 'Am',
    bpm: 68,
    status: 'ready',
    duration: '3:10',
  },
  {
    id: 't-2',
    order: 2,
    title: 'Walls of brick',
    leadMember: { id: 'mock-user-anna', name: 'Anna' },
    band: { id: 'band-1', name: 'Quiet Yard' },
    side: 'a',
    musicalKey: 'Dm',
    bpm: 80,
    status: 'ready',
    duration: '2:55',
  },
  {
    id: 't-3',
    order: 3,
    title: 'Lamps in the kitchen',
    leadMember: { id: 'mock-user-jared', name: 'Jared' },
    band: { id: 'band-1', name: 'Quiet Yard' },
    side: 'a',
    musicalKey: 'C',
    bpm: 96,
    status: 'ready',
    duration: '3:05',
  },
  {
    id: 't-4',
    order: 4,
    title: 'Outside of time',
    leadMember: { id: 'mock-user-artem', name: 'Artem' },
    band: { id: 'band-1', name: 'Quiet Yard' },
    side: 'a',
    musicalKey: 'Em',
    bpm: 60,
    status: 'ready',
    duration: '3:20',
  },
  {
    id: 't-5',
    order: 5,
    title: 'First snow',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-1', name: 'Quiet Yard' },
    side: 'b',
    musicalKey: 'G',
    bpm: 72,
    status: 'ready',
    duration: '3:15',
  },
  {
    id: 't-6',
    order: 6,
    title: 'Yards of childhood',
    leadMember: { id: 'mock-user-anna', name: 'Anna' },
    band: { id: 'band-1', name: 'Quiet Yard' },
    side: 'b',
    musicalKey: 'D',
    bpm: 88,
    status: 'learning',
    duration: '3:15',
  },

  // --- band-2 · Night Shift (8 tracks, 3 ready) ---
  {
    id: 't-7',
    order: 1,
    title: 'Night at the depot',
    leadMember: { id: 'mock-user-jared', name: 'Jared' },
    band: { id: 'band-2', name: 'Night Shift' },
    side: 'a',
    musicalKey: 'Am',
    bpm: 92,
    status: 'ready',
    duration: '3:48',
  },
  {
    id: 't-8',
    order: 2,
    title: 'Smoke over the city',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-2', name: 'Night Shift' },
    side: 'a',
    musicalKey: 'F',
    bpm: 96,
    status: 'ready',
    duration: '4:05',
  },
  {
    id: 't-9',
    order: 3,
    title: 'Coffee at six',
    leadMember: { id: 'mock-user-anna', name: 'Anna' },
    band: { id: 'band-2', name: 'Night Shift' },
    side: 'a',
    musicalKey: 'C',
    bpm: 108,
    status: 'ready',
    duration: '3:20',
  },
  {
    id: 't-10',
    order: 4,
    title: 'Trolleybus No.7',
    leadMember: { id: 'mock-user-artem', name: 'Artem' },
    band: { id: 'band-2', name: 'Night Shift' },
    side: 'a',
    musicalKey: 'Em',
    bpm: 124,
    status: 'learning',
    duration: '2:55',
  },
  {
    id: 't-11',
    order: 5,
    title: 'Last tram',
    leadMember: { id: 'mock-user-jared', name: 'Jared' },
    band: { id: 'band-2', name: 'Night Shift' },
    side: 'b',
    musicalKey: 'Am',
    bpm: 100,
    status: 'learning',
    duration: '3:40',
  },
  {
    id: 't-12',
    order: 6,
    title: 'Falling stars',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-2', name: 'Night Shift' },
    side: 'b',
    musicalKey: 'G',
    bpm: 84,
    status: 'new',
    duration: '4:30',
  },
  {
    id: 't-13',
    order: 7,
    title: 'Quiet harbour',
    leadMember: { id: 'mock-user-anna', name: 'Anna' },
    band: { id: 'band-2', name: 'Night Shift' },
    side: 'b',
    musicalKey: 'D',
    bpm: 72,
    status: 'new',
    duration: '5:50',
  },
  {
    id: 't-14',
    order: 8,
    title: 'Midnight shift',
    leadMember: { id: 'mock-user-artem', name: 'Artem' },
    band: { id: 'band-2', name: 'Night Shift' },
    side: 'b',
    musicalKey: 'Bm',
    bpm: 110,
    status: 'archived',
    duration: '4:02',
  },

  // --- band-3 · Broken Glass (6 tracks, 5 ready) ---
  {
    id: 't-15',
    order: 1,
    title: 'Shards of light',
    leadMember: { id: 'mock-user-artem', name: 'Artem' },
    band: { id: 'band-3', name: 'Broken Glass' },
    side: 'a',
    musicalKey: 'Bm',
    bpm: 104,
    status: 'ready',
    duration: '3:12',
  },
  {
    id: 't-16',
    order: 2,
    title: 'Cracked windows',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-3', name: 'Broken Glass' },
    side: 'a',
    musicalKey: 'E',
    bpm: 112,
    status: 'ready',
    duration: '2:58',
  },
  {
    id: 't-17',
    order: 3,
    title: 'Splinters',
    leadMember: { id: 'mock-user-anna', name: 'Anna' },
    band: { id: 'band-3', name: 'Broken Glass' },
    side: 'a',
    musicalKey: 'F#',
    bpm: 98,
    status: 'ready',
    duration: '3:24',
  },
  {
    id: 't-18',
    order: 4,
    title: 'Broken reflections',
    leadMember: { id: 'mock-user-jared', name: 'Jared' },
    band: { id: 'band-3', name: 'Broken Glass' },
    side: 'b',
    musicalKey: 'C#',
    bpm: 90,
    status: 'ready',
    duration: '3:33',
  },
  {
    id: 't-19',
    order: 5,
    title: 'Glass hearts',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-3', name: 'Broken Glass' },
    side: 'b',
    musicalKey: 'G#',
    bpm: 106,
    status: 'ready',
    duration: '3:05',
  },
  {
    id: 't-20',
    order: 6,
    title: 'Sharp edges',
    leadMember: { id: 'mock-user-artem', name: 'Artem' },
    band: { id: 'band-3', name: 'Broken Glass' },
    side: 'b',
    musicalKey: 'D#',
    bpm: 120,
    status: 'learning',
    duration: '2:48',
  },

  // --- band-4 · Dreamy Garden (14 tracks, 5 ready) ---
  {
    id: 't-21',
    order: 1,
    title: 'Petals falling slow',
    leadMember: { id: 'mock-user-anna', name: 'Anna' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'a',
    musicalKey: 'F#',
    bpm: 66,
    status: 'ready',
    duration: '4:32',
  },
  {
    id: 't-22',
    order: 2,
    title: 'Garden at dusk',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'a',
    musicalKey: 'A',
    bpm: 74,
    status: 'ready',
    duration: '3:41',
  },
  {
    id: 't-23',
    order: 3,
    title: 'Roses in rain',
    leadMember: { id: 'mock-user-jared', name: 'Jared' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'a',
    musicalKey: 'E',
    bpm: 70,
    status: 'ready',
    duration: '4:10',
  },
  {
    id: 't-24',
    order: 4,
    title: 'Wildflowers',
    leadMember: { id: 'mock-user-artem', name: 'Artem' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'a',
    musicalKey: 'D',
    bpm: 78,
    status: 'ready',
    duration: '3:55',
  },
  {
    id: 't-25',
    order: 5,
    title: 'Morning dew',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'a',
    musicalKey: 'G',
    bpm: 64,
    status: 'ready',
    duration: '4:20',
  },
  {
    id: 't-26',
    order: 6,
    title: 'Sunlit path',
    leadMember: { id: 'mock-user-anna', name: 'Anna' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'b',
    musicalKey: 'C',
    bpm: 82,
    status: 'learning',
    duration: '3:30',
  },
  {
    id: 't-27',
    order: 7,
    title: 'Butterfly wings',
    leadMember: { id: 'mock-user-jared', name: 'Jared' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'b',
    musicalKey: 'Bm',
    bpm: 90,
    status: 'learning',
    duration: '3:15',
  },
  {
    id: 't-28',
    order: 8,
    title: 'Garden gate',
    leadMember: { id: 'mock-user-artem', name: 'Artem' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'b',
    musicalKey: 'Am',
    bpm: 76,
    status: 'new',
    duration: '4:05',
  },
  {
    id: 't-29',
    order: 9,
    title: 'Secret meadow',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'b',
    musicalKey: 'F',
    bpm: 68,
    status: 'new',
    duration: '3:50',
  },
  {
    id: 't-30',
    order: 10,
    title: 'Ivy walls',
    leadMember: { id: 'mock-user-anna', name: 'Anna' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'b',
    musicalKey: 'Dm',
    bpm: 72,
    status: 'new',
    duration: '4:15',
  },
  {
    id: 't-31',
    order: 11,
    title: 'Fading blossoms',
    leadMember: { id: 'mock-user-jared', name: 'Jared' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'b',
    musicalKey: 'Em',
    bpm: 80,
    status: 'archived',
    duration: '3:20',
  },
  {
    id: 't-32',
    order: 12,
    title: 'Old greenhouse',
    leadMember: { id: 'mock-user-artem', name: 'Artem' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'b',
    musicalKey: 'G#',
    bpm: 62,
    status: 'archived',
    duration: '4:40',
  },
  {
    id: 't-33',
    order: 13,
    title: 'Thorns and dreams',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'b',
    musicalKey: 'C#',
    bpm: 84,
    status: 'archived',
    duration: '3:05',
  },
  {
    id: 't-34',
    order: 14,
    title: 'Winter garden',
    leadMember: { id: 'mock-user-anna', name: 'Anna' },
    band: { id: 'band-4', name: 'Dreamy Garden' },
    side: 'b',
    musicalKey: 'A#',
    bpm: 58,
    status: 'archived',
    duration: '4:55',
  },

  // --- band-5 · Pumpkin Square (9 tracks, 7 ready) ---
  {
    id: 't-35',
    order: 1,
    title: 'Square lanterns',
    leadMember: { id: 'mock-user-jared', name: 'Jared' },
    band: { id: 'band-5', name: 'Pumpkin Square' },
    side: 'a',
    musicalKey: 'G#',
    bpm: 118,
    status: 'ready',
    duration: '2:47',
  },
  {
    id: 't-36',
    order: 2,
    title: 'October wind',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-5', name: 'Pumpkin Square' },
    side: 'a',
    musicalKey: 'C#',
    bpm: 100,
    status: 'ready',
    duration: '3:19',
  },
  {
    id: 't-37',
    order: 3,
    title: 'Harvest moon',
    leadMember: { id: 'mock-user-anna', name: 'Anna' },
    band: { id: 'band-5', name: 'Pumpkin Square' },
    side: 'a',
    musicalKey: 'Bm',
    bpm: 92,
    status: 'ready',
    duration: '3:42',
  },
  {
    id: 't-38',
    order: 4,
    title: 'Pumpkin patch',
    leadMember: { id: 'mock-user-artem', name: 'Artem' },
    band: { id: 'band-5', name: 'Pumpkin Square' },
    side: 'a',
    musicalKey: 'E',
    bpm: 88,
    status: 'ready',
    duration: '3:10',
  },
  {
    id: 't-39',
    order: 5,
    title: 'Autumn leaves',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-5', name: 'Pumpkin Square' },
    side: 'a',
    musicalKey: 'D',
    bpm: 96,
    status: 'ready',
    duration: '3:25',
  },
  {
    id: 't-40',
    order: 6,
    title: "Scarecrow's tune",
    leadMember: { id: 'mock-user-jared', name: 'Jared' },
    band: { id: 'band-5', name: 'Pumpkin Square' },
    side: 'b',
    musicalKey: 'Am',
    bpm: 104,
    status: 'ready',
    duration: '2:58',
  },
  {
    id: 't-41',
    order: 7,
    title: 'Cider evening',
    leadMember: { id: 'mock-user-anna', name: 'Anna' },
    band: { id: 'band-5', name: 'Pumpkin Square' },
    side: 'b',
    musicalKey: 'F',
    bpm: 80,
    status: 'ready',
    duration: '3:33',
  },
  {
    id: 't-42',
    order: 8,
    title: 'Foggy square',
    leadMember: { id: 'mock-user-artem', name: 'Artem' },
    band: { id: 'band-5', name: 'Pumpkin Square' },
    side: 'b',
    musicalKey: 'Gm',
    bpm: 70,
    status: 'learning',
    duration: '4:02',
  },
  {
    id: 't-43',
    order: 9,
    title: 'Last of the light',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-5', name: 'Pumpkin Square' },
    side: 'b',
    musicalKey: 'Dm',
    bpm: 66,
    status: 'new',
    duration: '4:20',
  },

  // --- band-6 · Jellyfish (2 tracks, 0 ready) ---
  {
    id: 't-44',
    order: 1,
    title: 'Drifting slow',
    leadMember: { id: 'mock-user-artem', name: 'Artem' },
    band: { id: 'band-6', name: 'Jellyfish' },
    side: 'a',
    musicalKey: 'B',
    bpm: 58,
    status: 'new',
    duration: '5:02',
  },
  {
    id: 't-45',
    order: 2,
    title: 'Glow beneath',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-6', name: 'Jellyfish' },
    side: 'b',
    musicalKey: 'D#',
    bpm: 62,
    status: 'new',
    duration: '4:47',
  },
];
