import { Track } from '@nonsololarco/types';

export const MOCK_CURRENT_USER_ID = 'mock-user-solomiia';

export const MOCK_ALL_REPERTOIRE: Track[] = [
  {
    id: 't-1',
    order: 1,
    title: 'Yard in the fog',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-1', name: 'Quiet Yard' },
    side: 'a',
    musicalKey: 'Am',
    bpm: 68,
    status: 'ready',
    duration: '4:10',
  },
  {
    id: 't-2',
    order: 2,
    title: 'Walls of brick',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-1', name: 'Quiet Yard' },
    side: 'a',
    musicalKey: 'Dm',
    bpm: 80,
    status: 'learning',
    duration: '3:30',
  },
  {
    id: 't-3',
    order: 3,
    title: 'Lamps in the kitchen',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-1', name: 'Quiet Yard' },
    side: 'a',
    musicalKey: 'C',
    bpm: 96,
    status: 'ready',
    duration: '3:05',
  },
  {
    id: 't-4',
    order: 4,
    title: 'Outside of time',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-1', name: 'Quiet Yard' },
    side: 'a',
    musicalKey: 'Em',
    bpm: 60,
    status: 'new',
    duration: '5:20',
  },
  {
    id: 't-5',
    order: 5,
    title: 'First snow',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-1', name: 'Quiet Yard' },
    side: 'b',
    musicalKey: 'G',
    bpm: 72,
    status: 'archived',
    duration: '4:50',
  },
  {
    id: 't-6',
    order: 6,
    title: 'Yards of childhood',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-1', name: 'Quiet Yard' },
    side: 'b',
    musicalKey: 'D',
    bpm: 88,
    status: 'archived',
    duration: '3:55',
  },
  {
    id: 't-7',
    order: 1,
    title: 'Night at the depot',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-2', name: 'Night Shift' },
    side: 'a',
    musicalKey: 'Am',
    bpm: 92,
    status: 'ready',
    duration: '3:48',
  },
  {
    id: 't-8',
    order: 2,
    title: 'Smoke over the city',
    leadMember: { id: MOCK_CURRENT_USER_ID, name: 'Solomiia' },
    band: { id: 'band-2', name: 'Night Shift' },
    side: 'a',
    musicalKey: 'F',
    bpm: 96,
    status: 'ready',
    duration: '4:05',
  },
];
